/** 
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class ExtractedClass0 {
  private String password;
  private String email;
  private String username;
  public void createUser(  String u,  String e,  String p){
    this.username=u;
    this.email=e;
    this.password=p;
    System.out.println("User created: " + u);
  }
  public void sendEmail(){
    System.out.println("Sending email to " + email);
  }
  public String getPassword(){
    return this.password;
  }
  public void setPassword(  String value){
    this.password=value;
  }
  public String getEmail(){
    return this.email;
  }
  public void setEmail(  String value){
    this.email=value;
  }
  public String getUsername(){
    return this.username;
  }
  public void setUsername(  String value){
    this.username=value;
  }
}
