package org.apache.commons.lang3;
import java.util.UUID;
/** 
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class HexDigitConverter {
  /** 
 * Converts a hexadecimal digit into binary (represented as boolean array) using the MSB0 bit ordering. <p> '1' is converted as follow: (0, 0, 0, 1). </p>
 * @param hexChar the hexadecimal digit to convert.
 * @return a boolean array with the binary representation of {@code hexDigit}.
 * @throws IllegalArgumentException if {@code hexDigit} is not a hexadecimal digit.
 */
  public static boolean[] hexDigitMsb0ToBinary(  final char hexChar){
    return HexDigitConverter.hexDigitMsb0ToBinary(hexChar);
  }
  /** 
 * Converts a hexadecimal digit into an int using the MSB0 bit ordering. <p> '1' is converted to 8. </p>
 * @param hexChar the hexadecimal digit to convert.
 * @return an int equals to {@code hexDigit}.
 * @throws IllegalArgumentException if {@code hexDigit} is not a hexadecimal digit.
 */
  public static int hexDigitMsb0ToInt(  final char hexChar){
    return HexDigitConverter.hexDigitMsb0ToInt(hexChar);
  }
  /** 
 * Converts a hexadecimal digit into binary (represented as boolean array) using the default (LSB0) bit ordering. <p> '1' is converted as follow: (1, 0, 0, 0). </p>
 * @param hexChar the hexadecimal digit to convert.
 * @return a boolean array with the binary representation of {@code hexDigit}.
 * @throws IllegalArgumentException if {@code hexDigit} is not a hexadecimal digit.
 */
  public static boolean[] hexDigitToBinary(  final char hexChar){
    return HexDigitConverter.hexDigitToBinary(hexChar);
  }
  /** 
 * Converts a hexadecimal digit into an int using the default (LSB0) bit ordering. <p> '1' is converted to 1 </p>
 * @param hexChar the hexadecimal digit to convert.
 * @return an int equals to {@code hexDigit}.
 * @throws IllegalArgumentException if {@code hexDigit} is not a hexadecimal digit.
 */
  public static int hexDigitToInt(  final char hexChar){
    return HexDigitConverter.hexDigitToInt(hexChar);
  }
}
