package com.example.test;
/**
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class ArrayOperations {
  private int size;
  private int[] array;
  public void add(  int index,  int... values){
    for (    int value : values) {
      array[index++]=value;
      size++;
    }
  }
  public int[] insert(  int position,  int[] arr,  int... elements){
    int[] result=new int[arr.length + elements.length];
    System.arraycopy(arr,0,result,0,position);
    System.arraycopy(elements,0,result,position,elements.length);
    System.arraycopy(arr,position,result,position + elements.length,arr.length - position);
    return result;
  }
  public int getSize(){
    return this.size;
  }
  public void setSize(  int value){
    this.size=value;
  }
  public int incrementSize(){
    return ++this.size;
  }
  public int postIncrementSize(){
    return this.size++;
  }
  public int decrementSize(){
    return --this.size;
  }
  public int postDecrementSize(){
    return this.size--;
  }
  public int[] getArray(){
    return this.array;
  }
  public void setArray(  int[] value){
    this.array=value;
  }
}
