"""Shared data models for GenEC core modules.

This module centralises the key dataclasses that are exchanged across
the pipeline so that importers do not need to reach into implementation
modules (cluster_detector, llm_interface, verification_engine).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class QualityTier(Enum):
    """Quality tier for refactoring suggestions."""

    SHOULD = "should"  # High quality - strong recommendation
    COULD = "could"  # Medium quality - conditional recommendation
    POTENTIAL = "potential"  # Low quality - informational only


@dataclass
class Cluster:
    """Represents a detected cluster of methods and fields."""

    id: int
    member_names: list[str]
    member_types: dict[str, str] = field(default_factory=dict)  # name -> 'method' or 'field'
    quality_score: float = 0.0
    cohesion_coupling_score: float = 0.0
    modularity: float = 0.0
    internal_cohesion: float = 0.0
    external_coupling: float = 0.0
    rank_score: float | None = None
    rejection_issues: list = field(default_factory=list)

    # Advanced metrics
    silhouette_score: float | None = None
    conductance: float | None = None
    coverage: float | None = None
    is_connected: bool = True
    stability_score: float | None = None

    # Quality tier metadata
    quality_tier: QualityTier | None = None
    quality_reasons: list[str] = field(default_factory=list)

    def __len__(self):
        return len(self.member_names)

    def get_methods(self) -> list[str]:
        """Get only method members."""
        return [m for m, t in self.member_types.items() if t == "method"]

    def get_fields(self) -> list[str]:
        """Get only field members."""
        return [m for m, t in self.member_types.items() if t == "field"]


@dataclass
class RefactoringSuggestion:
    """Represents a refactoring suggestion generated by the LLM."""

    cluster_id: int
    proposed_class_name: str
    rationale: str
    new_class_code: str
    modified_original_code: str
    cluster: Cluster | None = None
    confidence_score: float | None = None  # 0-1 confidence rating
    reasoning: str | None = None  # Chain-of-thought reasoning

    # Naming diversity vote metadata
    naming_votes: list[dict] | None = None
    naming_agreement: float | None = None

    # Verification status
    verification_status: str | None = None

    # Quality tier metadata
    quality_tier: str | None = None  # "should", "could", or "potential"
    quality_score: float = 0.0
    quality_reasons: list[str] = field(default_factory=list)


@dataclass
class VerificationResult:
    """Result of multi-layer verification."""

    suggestion_id: int
    status: str
    equivalence_pass: bool = False  # Layer 0
    syntactic_pass: bool = False  # Layer 1
    quality_pass: bool = False  # Layer 1.5
    multiversion_pass: bool = False  # Layer 1.7
    semantic_pass: bool = False  # Layer 2
    behavioral_pass: bool = False  # Layer 3
    performance_pass: bool = False  # Layer 4
    tests_run: int = 0
    quality_improvement: float = 0.0
    performance_regression: float = 0.0
    error_message: str | None = None

    @property
    def is_valid(self) -> bool:
        """Return True only if overall verification status indicates pass."""
        return self.status in ("PASS", "PASSED", "PASSED_ALL", "VALID")
