package com.ecommerce.system;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;
/**
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class DiscountCalculator {
  private BigDecimal discountPercentage;
  private String customerTier;
  /**
 * Apply discount. Cohesion: HIGH - price calculation logic
 */
  public void applyDiscount(  BigDecimal percentage){
    if (percentage.compareTo(BigDecimal.ZERO) < 0 || percentage.compareTo(new BigDecimal("100")) > 0) {
      throw new IllegalArgumentException("Discount must be between 0 and 100");
    }
    this.discountPercentage=percentage;
    logAudit("Applied discount: " + percentage + "%");
    calculateTotalAmount();
  }
  /**
 * Apply customer tier discount. Cohesion: HIGH - price calculation logic
 */
  public void applyTierDiscount(){
switch (customerTier) {
case "GOLD":      applyDiscount(new BigDecimal("15"));
    break;
case "SILVER":  applyDiscount(new BigDecimal("10"));
break;
case "BRONZE":applyDiscount(new BigDecimal("5"));
break;
default:applyDiscount(BigDecimal.ZERO);
}
}
/**
 * Calculate total amount. Cohesion: HIGH - price calculation logic Challenge: Calls shipping calculation (cross-group dependency)
 */
public void calculateTotalAmount(){
priceCalculator.calculateTotalAmount();
}
/**
 * Log audit entry. Ambiguous: Logging could be separate concern or infrastructure
 */
public void logAudit(String message){
orderProcessor.logAudit(message);
}
public void setCustomerTier(String tier){
this.customerTier=tier;
logAudit("Customer tier set: " + tier);
}
public BigDecimal getDiscountPercentage(){
return this.discountPercentage;
}
public void setDiscountPercentage(BigDecimal value){
this.discountPercentage=value;
}
public String getCustomerTier(){
return this.customerTier;
}
public void setCustomerTier(String value){
this.customerTier=value;
}
}
