package com.ecommerce.system;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;
/**
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class OrderPriceCalculator {
  private PriceCalculator priceCalculator=new PriceCalculator();
  /**
 * Calculate discount amount. Cohesion: HIGH - price calculation logic
 */
  public BigDecimal getDiscountAmount(){
    return priceCalculator.getDiscountAmount();
  }
  /**
 * Calculate tax amount. Cohesion: HIGH - price calculation logic
 */
  public BigDecimal getTaxAmount(){
    return priceCalculator.getTaxAmount();
  }
  /**
 * Get price breakdown. Cohesion: HIGH - price calculation logic
 */
  public Map<String,BigDecimal> getPriceBreakdown(){
    return priceCalculator.getPriceBreakdown();
  }
  /**
 * Calculate shipping cost based on weight and destination. Cohesion: HIGH - shipping logic
 */
  public BigDecimal calculateShippingCost(){
    return priceCalculator.calculateShippingCost();
  }
  /**
 * Get shipping method multiplier. Cohesion: HIGH - shipping logic
 */
  public BigDecimal getShippingMethodMultiplier(){
    return priceCalculator.getShippingMethodMultiplier();
  }
  public BigDecimal getTotalAmount(){
    return priceCalculator.getTotalAmount();
  }
  public PriceCalculator getPriceCalculator(){
    return this.priceCalculator;
  }
  public void setPriceCalculator(  PriceCalculator value){
    this.priceCalculator=value;
  }
}
