package com.ecommerce.system;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;
/**
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class PriceCalculator {
  private BigDecimal taxRate;
  private BigDecimal shippingCost;
  private BigDecimal subtotal;
  /**
 * Calculate discount amount. Cohesion: HIGH - price calculation logic
 */
  public BigDecimal getDiscountAmount(){
    if (subtotal == null)     return BigDecimal.ZERO;
    return subtotal.multiply(discountPercentage).divide(new BigDecimal("100"));
  }
  /**
 * Calculate tax amount. Cohesion: HIGH - price calculation logic
 */
  public BigDecimal getTaxAmount(){
    if (subtotal == null)     return BigDecimal.ZERO;
    BigDecimal afterDiscount=subtotal.subtract(getDiscountAmount());
    return afterDiscount.multiply(taxRate);
  }
  /**
 * Calculate total amount. Cohesion: HIGH - price calculation logic Challenge: Calls shipping calculation (cross-group dependency)
 */
  public void calculateTotalAmount(){
    if (subtotal == null) {
      totalAmount=BigDecimal.ZERO;
      return;
    }
    BigDecimal afterDiscount=subtotal.subtract(getDiscountAmount());
    BigDecimal withTax=afterDiscount.add(getTaxAmount());
    if (shippingAddress != null) {
      shippingCost=calculateShippingCost();
    }
 else {
      shippingCost=BigDecimal.ZERO;
    }
    totalAmount=withTax.add(shippingCost);
  }
  /**
 * Get price breakdown. Cohesion: HIGH - price calculation logic
 */
  public Map<String,BigDecimal> getPriceBreakdown(){
    Map<String,BigDecimal> breakdown=new LinkedHashMap<>();
    breakdown.put("subtotal",subtotal != null ? subtotal : BigDecimal.ZERO);
    breakdown.put("discount",getDiscountAmount());
    breakdown.put("tax",getTaxAmount());
    breakdown.put("shipping",shippingCost != null ? shippingCost : BigDecimal.ZERO);
    breakdown.put("total",totalAmount != null ? totalAmount : BigDecimal.ZERO);
    return breakdown;
  }
  /**
 * Calculate shipping cost based on weight and destination. Cohesion: HIGH - shipping logic
 */
  public BigDecimal calculateShippingCost(){
    if (shippingAddress == null)     return BigDecimal.ZERO;
    packageWeight=items.stream().mapToDouble(item -> item.getWeight() * item.getQuantity()).sum();
    BigDecimal baseCost=new BigDecimal("5.00");
    BigDecimal weightCost=new BigDecimal(packageWeight).multiply(new BigDecimal("0.50"));
    BigDecimal internationalPremium="US".equals(shippingCountry) ? BigDecimal.ZERO : new BigDecimal("15.00");
    BigDecimal methodMultiplier=getShippingMethodMultiplier();
    return baseCost.add(weightCost).add(internationalPremium).multiply(methodMultiplier);
  }
  /**
 * Get shipping method multiplier. Cohesion: HIGH - shipping logic
 */
  public BigDecimal getShippingMethodMultiplier(){
    if (shippingMethod == null)     return BigDecimal.ONE;
switch (shippingMethod) {
case "STANDARD":      return BigDecimal.ONE;
case "EXPRESS":    return new BigDecimal("2.0");
case "OVERNIGHT":  return new BigDecimal("3.5");
default:return BigDecimal.ONE;
}
}
public BigDecimal getTotalAmount(){
return totalAmount;
}
public BigDecimal getTaxRate(){
return this.taxRate;
}
public void setTaxRate(BigDecimal value){
this.taxRate=value;
}
public BigDecimal getShippingCost(){
return this.shippingCost;
}
public void setShippingCost(BigDecimal value){
this.shippingCost=value;
}
public BigDecimal getSubtotal(){
return this.subtotal;
}
public void setSubtotal(BigDecimal value){
this.subtotal=value;
}
}
