package com.ecommerce.system;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;
/**
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class WarehouseInventoryTracker {
  private Map<String,Integer> warehouseStock;
  /**
 * Update warehouse stock. Cohesion: HIGH - inventory logic
 */
  public void updateWarehouseStock(  String productId,  int quantity){
    warehouseStock.put(productId,quantity);
    logAudit("Warehouse stock updated: " + productId + " = "+ quantity);
  }
  /**
 * Get low stock items. Cohesion: HIGH - inventory logic
 */
  public List<String> getLowStockItems(  int threshold){
    return warehouseStock.entrySet().stream().filter(entry -> entry.getValue() < threshold).map(Map.Entry::getKey).collect(Collectors.toList());
  }
  /**
 * Log audit entry. Ambiguous: Logging could be separate concern or infrastructure
 */
  public void logAudit(  String message){
    discountCalculator.logAudit(message);
  }
  public Map<String,Integer> getWarehouseStock(){
    return this.warehouseStock;
  }
  public void setWarehouseStock(  Map<String,Integer> value){
    this.warehouseStock=value;
  }
}
