package org.apache.commons.lang3;
import org.apache.commons.lang3.stream.Streams;
/** 
 * Extracted class generated by GenEC using Eclipse JDT.
 */
public class CharSetStringProcessor {
  /** 
 * CharSetUtils instances should NOT be constructed in standard programming. Instead, the class should be used as  {@code CharSetUtils.evaluateSet(null);}. <p>This constructor is public to permit tools that require a JavaBean instance to operate.</p>
 * @deprecated TODO Make private in 4.0.
 */
  @Deprecated public CharSetUtils(){
  }
}
